version: "3.8"

services:
  app:
    container_name: lookup2.0
    build: .
    ports:
      - "8080:8080"  # Ensure this matches your app's actual running port
    volumes:
      - .:/app
      - /app/node_modules  # Can be removed if causing issues
    env_file:
      - .env
    restart: unless-stopped
