version: "3.8"

services:
  app:
    container_name: lookup2.0
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    restart: unless-stopped
